export const LOGIN_INIT = 'LOGIN_INIT'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const DEPARTMENTS_INIT = 'DEPARTMENTS_INIT'
export const DEPARTMENTS_SUCCESS = 'DEPARTMENTS_SUCCESS'
export const DEPARTMENTS_ERROR = 'DEPARTMENTS_ERROR'

export const GET_USERS_INIT = 'GET_USERS_INIT'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_ERROR = 'GET_USERS_ERROR'

export const GET_MODULES_INIT = 'GET_MODULES_INIT'
export const GET_MODULES_SUCCESS = 'GET_MODULES_SUCCESS'
export const GET_MODULES_ERROR = 'GET_MODULES_ERROR'